### ISSUE TITLE
Videos on node/ hub are 0-10KB with nothing

### ISSUE THREAD

**Issue by cktech529** [groupon/Selenium-Grid-Extras#93]
I am seeing a ton of 0KB-10KB videos on nodes and these are being copied to the hub.

**Comment by mstankovic86** [comment]
I have the same problem.

**Comment by dmhalejr** [comment]
I created a `node/hub` variation on a Ubuntu VM running 12.04. 

After kicking off a few tests from my local machine to the remote instance I did receive a few mp4 files, but all the files generated were kilobytes large. 
![screen shot 2015-03-06 at 9 05 11 pm](https://cloud.githubusercontent.com/assets/2513519/6539811/2ef8363a-c445-11e4-9dce-a5bd0f5595ee.png)

I took example steps from the supplied JSON example and put it into `selenium_grid_extras_config.json`. I then restarted Selenium-Grid-Extras, but I have had no luck thus far. 

Is there a compatibility issue with the video functionality of Extras with Ubuntu or am I missing a step? 

The ease in which I was able to get Extras up and running while also dismantling my old infrastructure took me less than a day and I thank you for that. Just wanted to get this new bells and whistles feature up and running or at least understand its limitation. 

Thanks!

**JSON**:
```
{
  "theConfigMap": {
    "auto_start_hub": "1",
    "default_role": "hub",
    "video_recording_options": {
      "height": "768",
      "frameSeconds": "1",
      "idle_video_timeout": "120",
      "frames": "5",
      "title_frame_font_color": "129,182,64,128",
      "lower_third_background_color": "0,0,0,200",
      "width": "1024",
      "lower_third_font_color": "255,255,255,255",
      "video_output_dir": "video_output",
      "record_test_videos": "true",
      "videos_to_keep": "40"
    },
    "node_config_files": [
      "node_5555.json"
    ],
    "active_modules": [
      "com.groupon.seleniumgridextras.tasks.Setup",
      "com.groupon.seleniumgridextras.tasks.Teardown",
      "com.groupon.seleniumgridextras.tasks.MoveMouse",
      "com.groupon.seleniumgridextras.tasks.RebootNode",
      "com.groupon.seleniumgridextras.tasks.VideoRecorder",
      "com.groupon.seleniumgridextras.tasks.KillAllIE",
      "com.groupon.seleniumgridextras.tasks.KillAllFirefox",
      "com.groupon.seleniumgridextras.tasks.KillAllChrome",
      "com.groupon.seleniumgridextras.tasks.KillAllSafari",
      "com.groupon.seleniumgridextras.tasks.GetProcesses",
      "com.groupon.seleniumgridextras.tasks.KillPid",
      "com.groupon.seleniumgridextras.tasks.Netstat",
      "com.groupon.seleniumgridextras.tasks.Screenshot",
      "com.groupon.seleniumgridextras.tasks.ExposeDirectory",
      "com.groupon.seleniumgridextras.tasks.StartGrid",
      "com.groupon.seleniumgridextras.tasks.GetInfoForPort",
      "com.groupon.seleniumgridextras.tasks.GridStatus",
      "com.groupon.seleniumgridextras.tasks.KillAllByName",
      "com.groupon.seleniumgridextras.tasks.StopGrid",
      "com.groupon.seleniumgridextras.tasks.GetConfig",
      "com.groupon.seleniumgridextras.tasks.StopGridExtras",
      "com.groupon.seleniumgridextras.tasks.IEProtectedMode",
      "com.groupon.seleniumgridextras.tasks.IEMixedContent",
      "com.groupon.seleniumgridextras.tasks.SystemInfo",
      "com.groupon.seleniumgridextras.tasks.GetNodeConfig",
      "com.groupon.seleniumgridextras.tasks.UpdateNodeConfig",
      "com.groupon.seleniumgridextras.tasks.AutoUpgradeDrivers",
      "com.groupon.seleniumgridextras.tasks.DownloadWebdriver",
      "com.groupon.seleniumgridextras.tasks.DownloadIEDriver",
      "com.groupon.seleniumgridextras.tasks.DownloadChromeDriver",
      "com.groupon.seleniumgridextras.tasks.SessionHistory"
    ],
    "hub_config": {},
    "hub_config_files": [
      "hub_4444.json"
    ],
    "iedriver": {
      "version": "2.45.0"
    },
    "auto_start_node": "1",
    "auto_update_drivers": "1",
    "chromedriver": {
      "version": "2.14"
    },
    "webdriver": {
      "version": "2.45.0"
    }
  }
}
```

**Comment by Djamiyo** [comment]
I have the same problem on Windows 7. All video files are exactly 65 536 bytes and marked as corrupted. VLC player shows that it can't detect file's format.

![](http://screen.fst.su/djam-12.03.2015-17.04.03.png)

**Comment by Djamiyo** [comment]
I guess there are some problem with building video url (part of grid_extras.log):

```
16 мар 2015 18:44:26 [Matcher thread] INFO  threads.RemoteGridExtrasAsyncCallable  - Attempting to notify 10.100.100.171 (3000) of action: /setup with params {}
16 мар 2015 18:44:26 [Matcher thread] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://10.100.100.171:5555, int key: 90ae290c-1b9f-4679-923c-ae034a1d8123, ex. key: [no key assigned yet], action: start, lastAction: 
16 мар 2015 18:44:31 [Forwarding ext. key e635ed8c-f58a-4c1a-80db-d08091a5f493 to http://10.100.100.171:5555/wd/hub at 18:44:31] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://10.100.100.171:5555, int key: 90ae290c-1b9f-4679-923c-ae034a1d8123, ex. key: e635ed8c-f58a-4c1a-80db-d08091a5f493, action: heartbeat, lastAction: maximizeWindow: {":windowHandle":"current"}
16 мар 2015 18:44:31 [pool-1-thread-2] ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 10.100.100.171, port: e635ed8c-f58a-4c1a-80db-d08091a5f493, session: 3000, action: heartbeat, params: {session=e635ed8c-f58a-4c1a-80db-d08091a5f493, action=heartbeat, description=maximizeWindow: {":windowHandle":"current"}}
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
	at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequest(HttpUtility.java:60)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:35)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:29)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:25)
	at com.groupon.seleniumgridextras.videorecording.RemoteVideoRecorderHelper.updateLastAction(RemoteVideoRecorderHelper.java:109)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.updateLastAction(RemoteVideoRecordingControlCallable.java:112)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:65)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:11)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```
Closer look at port and session params:
```
building URI for host: 10.100.100.171, port: e635ed8c-f58a-4c1a-80db-d08091a5f493, session: 3000
```

**Comment by Djamiyo** [comment]
It has been fixed 26 days ago: [commit](https://github.com/groupon/Selenium-Grid-Extras/commit/d8e2ba992c57807b338177e7e9c5bb9f3cdf9c0e). Where would be a new release? The latest one was 30 Oct 2014.

**Comment by ranasingh** [comment]
I just downloaded and built from the git repo and run the grid, but I still get the same error message as you, so does not look like the fix you are referring to adresses the issue. Can anyone confirm that the video-issue in this thread still is not solved?

**Comment by Djamiyo** [comment]
I can confirm, that the problem still exists. The latest build still has the same problem. I'm not a Selenium Grid Extras developer, so my previous comment was just a guess. Sorry for misunderstanding.

**Comment by mrfreester** [comment]
The commit activity seems to be getting less frequent unfortunately. This would be a very helpful feature but I'm not sure I want to wait around for it. I'm considering going back to a build where the videos were working. Does anybody have information about which release these videos stopped working in?

**Comment by dmhalejr** [comment]
Since the commit activity is going down I think I'd rather take my changes with old Selenium Grid. I got excited to utilize this tool, but it's been too difficult to work with. Especially when the hope was to utilize it for all the bells and whistles.

**Comment by bbhenry** [comment]
Video isn't working for me on Windows 7 either. Using the latest stable build 1.10.0

**Comment by smccarthy** [comment]
@bbhenry By not working, are the video files all 0-10KB with nothing to show? I want to make sure its the same issue and not a different one.

@dmhalejr @mrfreester @Djamiyo @ranasingh @mstankovic86 @cktech529 I will try to check this issue out this weekend.

**Comment by nvonop** [comment]
@smccarthy have you had a chance to look at this yet?  Really excited to see this working!

With the latest release I have seen video files getting created of a size I would expect but have been unable to play them either through the browser of through VLC.

**Comment by smccarthy** [comment]
@nvonop Sorry not yet. Are they all getting created of size? or are some still being created 0-1KB ? Are you using Windows 7 ? or a different OS? If possible, can you send me one of the video files that don't play?

I also hang out in the #selenium irc channel on freenode (as smccarthy) if you want to debug the issue there.

Thank you.

**Comment by Dveryby** [comment]
Hi,

I have the same problem on Win7 and grid version 1.10.1-SNAPSHOT. Almost all files are 65 536 bytes and cannot be played. Some files are less the 65 536 bytes and these can be played but I can see only black screen on them.
I can send a sample files.

**Comment by rhehl** [comment]
Hi,
it look's like a problem with the Video download to the HUB, i tryed many OS combinations without success.

Going back to an older SeleniumGridExtras version (without Video 2 Hub Downloading) Fixes the Video Recording.

Logfile:
25 Aug 2015 16:00:08 [Forwarding ext. key 01494bbb-dfaf-4572-b857-897706aec339 to http://192.168.198.128:5555/wd/hub at 16:00:08] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.198.128:5555, int key: b61c62ad-c7e9-410c-a5f9-cb1eb2f91bf7, ex. key: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, lastAction: findChildElements: {"using":"css selector","value":"div[data-accordion-id=\"***************\"]"}
25 Aug 2015 16:00:08 [pool-1-thread-16] ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 192.168.198.128, port: 3000, session: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, params: {session=01494bbb-dfaf-4572-b857-897706aec339, action=heartbeat, description=findChildElements: {"using":"css selector","value":"div[data-accordion-id=\"******************\"]"}}
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequest(HttpUtility.java:59)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:34)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:28)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:24)
	at com.groupon.seleniumgridextras.videorecording.RemoteVideoRecorderHelper.updateLastAction(RemoteVideoRecorderHelper.java:109)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.updateLastAction(RemoteVideoRecordingControlCallable.java:112)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:65)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
25 Aug 2015 16:00:08 [Forwarding ext. key 01494bbb-dfaf-4572-b857-897706aec339 to http://192.168.198.128:5555/wd/hub at 16:00:08] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.198.128:5555, int key: b61c62ad-c7e9-410c-a5f9-cb1eb2f91bf7, ex. key: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, lastAction: findChildElements: {"using":"xpath","value":".."}
25 Aug 2015 16:00:08 [pool-1-thread-16] ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 192.168.198.128, port: 3000, session: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, params: {session=01494bbb-dfaf-4572-b857-897706aec339, action=heartbeat, description=findChildElements: {"using":"xpath","value":".."}}
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequest(HttpUtility.java:59)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:34)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:28)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:24)
	at com.groupon.seleniumgridextras.videorecording.RemoteVideoRecorderHelper.updateLastAction(RemoteVideoRecorderHelper.java:109)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.updateLastAction(RemoteVideoRecordingControlCallable.java:112)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:65)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
25 Aug 2015 16:00:08 [Forwarding ext. key 01494bbb-dfaf-4572-b857-897706aec339 to http://192.168.198.128:5555/wd/hub at 16:00:08] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.198.128:5555, int key: b61c62ad-c7e9-410c-a5f9-cb1eb2f91bf7, ex. key: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, lastAction: findChildElements: {"using":"css selector","value":".accordion__toggle.icon--arrow-double-large-down"}
25 Aug 2015 16:00:08 [pool-1-thread-16] ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 192.168.198.128, port: 3000, session: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, params: {session=01494bbb-dfaf-4572-b857-897706aec339, action=heartbeat, description=findChildElements: {"using":"css selector","value":".accordion__toggle.icon--arrow-double-large-down"}}
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequest(HttpUtility.java:59)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:34)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:28)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:24)
	at com.groupon.seleniumgridextras.videorecording.RemoteVideoRecorderHelper.updateLastAction(RemoteVideoRecorderHelper.java:109)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.updateLastAction(RemoteVideoRecordingControlCallable.java:112)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:65)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
25 Aug 2015 16:00:08 [Forwarding ext. key 01494bbb-dfaf-4572-b857-897706aec339 to http://192.168.198.128:5555/wd/hub at 16:00:08] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.198.128:5555, int key: b61c62ad-c7e9-410c-a5f9-cb1eb2f91bf7, ex. key: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, lastAction: clickElement: {}
25 Aug 2015 16:00:08 [pool-1-thread-16] ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 192.168.198.128, port: 3000, session: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, params: {session=01494bbb-dfaf-4572-b857-897706aec339, action=heartbeat, description=clickElement: {}}
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequest(HttpUtility.java:59)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:34)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:28)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:24)
	at com.groupon.seleniumgridextras.videorecording.RemoteVideoRecorderHelper.updateLastAction(RemoteVideoRecorderHelper.java:109)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.updateLastAction(RemoteVideoRecordingControlCallable.java:112)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:65)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
25 Aug 2015 16:00:08 [Forwarding ext. key 01494bbb-dfaf-4572-b857-897706aec339 to http://192.168.198.128:5555/wd/hub at 16:00:08] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.198.128:5555, int key: b61c62ad-c7e9-410c-a5f9-cb1eb2f91bf7, ex. key: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, lastAction: findElements: {"using":"css selector","value":".main__content"}

**Comment by rhehl** [comment]
@smccarthy maybe "ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 192.168.198.128, port: 3000, session: 01494bbb-dfaf-4572-b857-897706aec339, action: heartbeat, params: {session=01494bbb-dfaf-4572-b857-897706aec339, action=heartbeat, description=findElements: {"using":"css selector","value":".main__content"}}" is the Main Problem?

**Comment by rhehl** [comment]
I got it workig:

1. I Downloadet the Current Master Branch as ZIP
2. Extracted it
3. In SeleniumGridExtras\src\test\java\com\groupon\seleniumgridextras\utilities\ValueConverterTest.java I removed 
@Test
    public void testBytesToHumanReadable() throws Exception {
        assertEquals("20.0 MB", ValueConverter.bytesToHumanReadable(20000000, true));
        assertEquals("19.1 MiB", ValueConverter.bytesToHumanReadable(20000000, false));
    }
Couse it fails the build outside US (because the 20,0 MB instead of 20.0 MB)
4. In SeleniumGridExtras\src\main\java\com\groupon\seleniumgridextras\videorecording\RemoteVideoRecorderHelper.java
i commented out inside the methode "updateLastAction(String host, String session, String action)"
 builder.addParameter(p, params.get(p));
before:
    for (String p : params.keySet()) {
                builder.addParameter(p, params.get(p));
            }
now:
    for (String p : params.keySet()) {
                //builder.addParameter(p, params.get(p));
            }
5. I run release_prep.sh
And the resulting Selenium-Grid-Extras-master/SeleniumGridExtras/target/SeleniumGridExtras-1.11.1-SNAPSHOT-jar-with-dependencies.jar records now Videos

P.S.: I don't now if the Curent Master is fixed or if commenting the stuff out fixes it.

**Comment by dimacus** [comment]
@rhehl hmm the divisible by 2 does hit my memory somewhere, i remember there might have been an h264 enforcement of that rule or something. Let me check the code

**Comment by dimacus** [comment]
@rhehl thanks for the heads up i've added this warning to the video recorder. Can we close this ticket?

https://github.com/groupon/Selenium-Grid-Extras/blob/master/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/utilities/threads/video/VideoRecorderCallable.java#L53-L58

**Comment by rhehl** [comment]
![sel](https://cloud.githubusercontent.com/assets/7577984/10365430/8c838868-6dc3-11e5-8eaa-e2b5ffe7f84a.PNG)

still broken :/ during testing everything is fine, but at the end it got broken

**Comment by cktech529** [comment]
I'm still seeing this:

1.10.1

![image](https://cloud.githubusercontent.com/assets/6800679/10377325/9b9ff6bc-6dd0-11e5-89c8-a147e7ae6c36.png)

**Comment by pussinboots** [comment]
Hi,

i have the same problem like the last mentioned see a lot of files with size zero. But the video get recored if the test is running but when the webdriver.quit() is called in the TestCase then the working video file shrink to zero. Add a Thread.sleep to my test and copy the file before webdriver.quit() was called. That video was working. The used OS is WIndows 7 and versions 1.10.1

Did a little research and it seems that 

16 Oct 2015 13:35:28 [Thread-15] INFO  threads.RemoteGridExtrasAsyncCallable  - Attempting to notify 192.168.6.16 (3000) of action: /kill_ie with params {}
16 Oct 2015 13:35:28 [Thread-15] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.6.16:5555, int key: 602cd293-79ae-418a-ac94-45089fa0f407, ex. key: 9f670fc5-e364-4544-bc13-fbf1267a85ec, action: stop, lastAction: 

this action overwrite the working video file with the zero once.
Append a little bit of logging message.

May some has a hint for me. Will also look a little bit deeper in the Code


16 Oct 2015 13:33:04 [Thread-14] INFO  video.VideoDownloaderCallable  - New instance for session: 0c19ee16-f626-43f6-9bdc-a39a96614c0f host: 192.168.6.16
16 Oct 2015 13:33:04 [Thread-14] INFO  video.VideoDownloaderCallable  - Built URI http://192.168.6.16:3000/video
16 Oct 2015 13:33:04 [Thread-14] INFO  threads.RemoteGridExtrasAsyncCallable  - Attempting to notify 192.168.6.16 (3000) of action: /teardown with params {}
16 Oct 2015 13:33:04 [pool-1-thread-4] INFO  video.VideoDownloaderCallable  - Attempt 0 of 5 to download test video for session 0c19ee16-f626-43f6-9bdc-a39a96614c0f from host 192.168.6.16
16 Oct 2015 13:33:05 [pool-1-thread-6] INFO  threads.NodeRestartCallable  - Giving http://192.168.6.16:5555 proxy 2000 ms to free up
16 Oct 2015 13:33:07 [Thread-7] INFO  seleniumgridextras.VideoHttpExecutor  - Setting video source directory to C:\seleniumgrid\video_output
16 Oct 2015 13:33:07 [Thread-7] INFO  seleniumgridextras.VideoHttpExecutor  - New video download request for C:\seleniumgrid\video_output\0c19ee16-f626-43f6-9bdc-a39a96614c0f.mp4
16 Oct 2015 13:33:07 [Thread-7] INFO  seleniumgridextras.VideoHttpExecutor  - Requested video C:\seleniumgrid\video_output\0c19ee16-f626-43f6-9bdc-a39a96614c0f.mp4 does exist, responding with 404
16 Oct 2015 13:33:07 [pool-1-thread-4] INFO  video.VideoDownloaderCallable  - Successfully downloaded video for session 0c19ee16-f626-43f6-9bdc-a39a96614c0f, from host 192.168.6.16, to directory on hub C:\seleniumgrid\video_output\0c19ee16-f626-43f6-9bdc-a39a96614c0f.mp4
16 Oct 2015 13:33:07 [pool-1-thread-6] INFO  threads.RemoteGridExtrasAsyncCallable  - Attempting to notify 192.168.6.16 (3000) of action: /grid_status with params {}
16 Oct 2015 13:33:59 [Matcher thread] INFO  threads.RemoteGridExtrasAsyncCallable  - Attempting to notify 192.168.6.16 (3000) of action: /setup with params {}
16 Oct 2015 13:33:59 [Matcher thread] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.6.16:5555, int key: 602cd293-79ae-418a-ac94-45089fa0f407, ex. key: [no key assigned yet], action: start, lastAction: 
16 Oct 2015 13:33:59 [pool-1-thread-6] INFO  threads.SessionHistoryCallable  - Waiting for internal key 602cd293-79ae-418a-ac94-45089fa0f407, to get an external key
16 Oct 2015 13:34:02 [pool-1-thread-6] INFO  threads.SessionHistoryCallable  - Associating internal key 9f670fc5-e364-4544-bc13-fbf1267a85ec to external key 9f670fc5-e364-4544-bc13-fbf1267a85ec
16 Oct 2015 13:34:02 [pool-1-thread-6] INFO  loggers.SessionHistoryLog  - Registering new session to file C:\seleniumgrid\log\session_logs\192.168.6.16_16_10_2015.log
16 Oct 2015 13:34:02 [pool-1-thread-6] INFO  threads.SessionHistoryCallable  - Notifying Remote Grid Extras node of new session with http://192.168.6.16:3000/grid_status?session=9f670fc5-e364-4544-bc13-fbf1267a85ec
16 Oct 2015 13:34:02 [Thread-7] INFO  tasks.VideoRecorder  - Starting video recording for session: 9f670fc5-e364-4544-bc13-fbf1267a85ec, on host: 192.168.6.16, done: false, cancelled: false
16 Oct 2015 13:34:02 [pool-2-thread-2] INFO  video.VideoRecorderCallable  - Starting video recording for session 9f670fc5-e364-4544-bc13-fbf1267a85ec to C:\seleniumgrid\video_output
16 Oct 2015 13:34:07 [Forwarding ext. key 9f670fc5-e364-4544-bc13-fbf1267a85ec to http://192.168.6.16:5555/wd/hub at 1:34:07 PM] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.6.16:5555, int key: 602cd293-79ae-418a-ac94-45089fa0f407, ex. key: 9f670fc5-e364-4544-bc13-fbf1267a85ec, action: heartbeat, lastAction: get: {"url":"http://192.168.1.14:8080/ReqIF/html/import.html?sessionId=832631&authentificated=ORCL:1633755C37CA017E8F76853B962ED8146AA366B41CA1B00BFFA3A59A38A51AE85962814852B6A5804EA54936FAC25A0DF7409D9A4926A0772CB776F818B049C4B5F153C36884241200136E22055E311D28CEDF0FAF376605D899E2E98BE22CCB5CF5B19920CC647ABF16E3ADBAE7897B43BC98A21D8C8738FB14E5851F6A74787C6FC7E17E9663B1"}
....
16 Oct 2015 13:35:27 [Forwarding ext. key 9f670fc5-e364-4544-bc13-fbf1267a85ec to http://192.168.6.16:5555/wd/hub at 1:35:27 PM] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.6.16:5555, int key: 602cd293-79ae-418a-ac94-45089fa0f407, ex. key: 9f670fc5-e364-4544-bc13-fbf1267a85ec, action: heartbeat, lastAction: quit: 
16 Oct 2015 13:35:28 [Thread-15] INFO  threads.RemoteGridExtrasAsyncCallable  - Attempting to notify 192.168.6.16 (3000) of action: /kill_ie with params {}
16 Oct 2015 13:35:28 [Thread-15] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://192.168.6.16:5555, int key: 602cd293-79ae-418a-ac94-45089fa0f407, ex. key: 9f670fc5-e364-4544-bc13-fbf1267a85ec, action: stop, lastAction: 
16 Oct 2015 13:35:30 [Thread-7] INFO  video.VideoRecordingThreadPool  - Politely asking video recording to stop
16 Oct 2015 13:35:31 [Thread-7] INFO  video.VideoRecordingThreadPool  - Video for session 9f670fc5-e364-4544-bc13-fbf1267a85ec has stopped.

**Comment by rhehl** [comment]
same problem with Version : 1.11.8-SNAPSHOT during testing the video file grows, after testing it shriks to 64kb

**Comment by mjevtovic** [comment]
Is there a solution for this? I am running into same issue on 1.11.8-SNAPSHOT. It's quite random, sometimes file is 0kb sometimes it's bigger but can't be played, sometimes it's recorded successfully and is watchable.

**Comment by bethrezen** [comment]
My investigation tells that this happens when down TeardownProxy attempts to download video.
I think it's only reproducible only on configurations where hub and node are the same machine(as i understood hub tries to download video from node and it writes to the same file it reads). 
Therefore, quick fix is to comment out these lines in SetupTeardownProxy::afterSession -> https://github.com/groupon/Selenium-Grid-Extras/blob/3b10c02b05ad436d4c99beec3dfedc506c57d1ae/SeleniumGridExtras/src/main/java/com/groupon/seleniumgridextras/grid/proxies/SetupTeardownProxy.java#L165-L173

**Comment by rhehl** [comment]
Depending on bethrezen's investigation my suggestion would be:

change line 168 to:
            if (RuntimeConfig.getConfig().getVideoRecording().getVideosToKeep() > 0 && !(RuntimeConfig.getConfig().getAutoStartHub() && RuntimeConfig.getConfig().getAutoStartNode())) {

**Comment by smccarthy** [comment]
@rhehl Thanks ! I will look into merging this one.

**Comment by dmitriivoitovich** [comment]
@dimacus Is there any estimate for new release date? If this changes fix the issue it's rather important.

**Comment by eyal919** [comment]
Fixed? is there workaround for this issue? 
I'm have grid hub on linux server and node on win7 but still getting 0 size video with the next error on hub log:

21 Jun 2016 12:27:29 [Forwarding ext. key a30316bf-8d81-4dce-a962-bb1bd25f4ac1 to http://172.30.22.22:5555/wd/hub at 12:27:29 PM] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://172.30.22.22:5555, int key: 3aaad437-aacb-4f99-a4a4-c8d8fc6597d8, ex. key: a30316bf-8d81-4dce-a962-bb1bd25f4ac1, action: heartbeat, lastAction: getElementAttribute:
21 Jun 2016 12:27:29 [pool-1-thread-7] ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 172.30.22.22, port: 3000, session: a30316bf-8d81-4dce-a962-bb1bd25f4ac1, action: heartbeat, params: {session=a30316bf-8d81-4dce-a962-bb1bd25f4ac1, action=heartbeat, description=getElementAttribute: }
java.net.SocketException: Unexpected end of file from server
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:792)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:789)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequest(HttpUtility.java:60)
        at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:35)
        at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:29)
        at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:25)
        at com.groupon.seleniumgridextras.videorecording.RemoteVideoRecorderHelper.updateLastAction(RemoteVideoRecorderHelper.java:109)
        at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.updateLastAction(RemoteVideoRecordingControlCallable.java:112)
        at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:65)
        at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:11)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by smccarthy** [comment]
@eyal919 Which version of selenium grid extras are you using? Its very possible this is still an issue. I don't know much about the video recording part of selenium-grid-extras. I did merge https://github.com/groupon/Selenium-Grid-Extras/pull/198 in back in February, and there has been a release since then.

**Comment by filcasidy** [comment]
I got the same Problem with Videos (Black screen and the filesizes are 7Kb) but there is no Error message just: 
27 Jul 2016 11:37:32 [pool-2-thread-1] INFO  video.VideoRecorderCallable  - Starting video recording for session 1448fbc8-5b72-4a42-a759-95fcedc82213 to C:\Users\selenium\Desktop\Selenium\video_output
27 Jul 2016 11:37:34 [Thread-13] INFO  video.VideoRecordingThreadPool  - Video Session 1448fbc8-5b72-4a42-a759-95fcedc82213 seems to have timed out, removing it from memory
27 Jul 2016 11:37:44 [Thread-13] INFO  seleniumgridextras.VideoHttpExecutor  - Setting video source directory to C:\Users\selenium\Desktop\Selenium\video_output

Version: 1.12.3-SNAPSHOT on Windows 10

Does anybody has a solution for it?

**Comment by YogiBear52** [comment]
I had the same problem. The logs files indicated the hub is trying to reach the node with an hub api. 
Starting a Hub next to each Node has solved the problem. It is strange because these hubs has no nodes registered and doing nothing but recording videos.
I have no idea if this is a workaround or the proper way to record video.
